name: Deploy ARM Template

on:
  push:
    branches:
      - master  # Trigger on push to the 'master' branch (you can change to any branch you want)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Azure CLI
    - name: Set up Azure CLI
      uses: azure/CLI@v1  # Ensure this version is correct
      with:
        inlineScript: |
          # Check the version of Azure CLI to verify it's set up correctly
          az --version

    # Step 3: Login to Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true


    # Step 4: Validate ARM template (Optional but recommended)
    - name: Validate ARM Template
      run: |
        az deployment group validate \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --template-file ./path/to/your-arm-template.json \
          --parameters ./path/to/your-parameters.json
      continue-on-error: true  # Continue even if validation fails (you can remove this for strict failure)

    # Step 5: Deploy ARM Template
    - name: Deploy ARM Template
      run: |
        az deployment group create \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --template-file ./path/to/template.json \
          --parameters ./path/to/parameters.json

    # Step 6: Clean up temporary files (if any)
    - name: Clean up temporary files
      run: |
        rm -rf ./path/to/temporary-files/
