name: Deploy ARM Template to Azure

# Trigger the workflow automatically on push to the 'main' branch
on:
  push:
    branches:
      - main  # This will trigger the workflow on push to 'main' (change if using another branch)
  workflow_dispatch:  # Optional: Allows for manual trigger via GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for the job

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3  # Checks out the code from the repository

      # Step 2: Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1
        with:
          version: '2.32.0'  # Specify the Azure CLI version to use

      # Step 3: Log in to Azure using Service Principal credentials from GitHub secrets
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      # Step 4: Validate ARM template (Optional but recommended)
      - name: Validate ARM Template
        run: |
          az deployment group validate \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --template-file arm-template.json \
            --parameters parameters.json
        continue-on-error: true  # Continue even if validation fails (you can remove this for strict failure)

      # Step 5: Deploy ARM Template using the template and parameters file
      - name: Deploy ARM Template
        run: |
          az deployment group create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --template-file arm-template.json \
            --parameters parameters.json
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 6: Verify the deployment (Optional)
      - name: Verify Deployment
        run: |
          # Optional: Check the deployment status or any resources to verify the deployment
          az deployment group show --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name your-deployment-name
